api_platform:
    # The title of the API.
    title: 'Edo, the fictio API'

    # The description of the API.
    description: 'Edo the API of fictio = a tool for creating fictions.'

    # The version of the API.
    version: '0.0.1'

    # Set this to false if you want Webby to disappear.
    show_webby: false

    mapping:
        paths: ['%kernel.project_dir%/src/Component/DTO']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

