language: php

php:
    - '7.3'

addons:
    postgresql: "12.1"

install:
    - cp .env.test.dist .env.test
    - composer install
    - ./bin/phpunit install

#script:
#    - php bin/console doctrine:database:create --env=test
#    - php bin/console --no-interaction doctrine:schema:update  --force --env=test